ref: prevent test pollution from not-always-registered signal in #55091 (#55785)
the hook in #55091 is not consistently registered causing `name` to
inconsistently be removed depending on whether the module has been
imported or not (a common side-effect from other tests in the module):

```console
$ pytest -qq tests/sentry/integrations/slack/test_tasks.py::SlackTasksTest::test_task_existing_rule tests/sentry/integrations/slack/test_uninstall.py::SlackUninstallTest::test_uninstall_slack_only
F.                                                                                                                        [100%]
=========================================================== FAILURES ============================================================
____________________________________________ SlackTasksTest.test_task_existing_rule _____________________________________________
tests/sentry/integrations/slack/test_tasks.py:162: in test_task_existing_rule
    assert updated_rule.data["actions"] == [
E   AssertionError: assert [{'channel': ...cation', ...}] == [{'channel': ...gs': '', ...}]
E     At index 0 diff: {'channel': '#my-channel', 'id': 'sentry.integrations.slack.notify_action.SlackNotifyServiceAction', 'name': 'Send a notification to the funinthesun Slack workspace to #secrets and show tags [] in notification', 'tags': '', 'workspace': 1, 'channel_id': 'chan-id'} != {'channel': '#my-channel', 'channel_id': 'chan-id', 'id': 'sentry.integrations.slack.notify_action.SlackNotifyServiceAction', 'tags': '', 'workspace': 1}
E     Use -v to get more diff
==================================================== short test summary info ====================================================
FAILED tests/sentry/integrations/slack/test_tasks.py::SlackTasksTest::test_task_existing_rule - AssertionError: assert [{'channel': ...cation', ...}] == [{'channel': ...gs': '', ...}]
```

<!-- Describe your PR here. -->