ref: require `choices` for ChoiceField to be a Sequence (#53707)
fixed the one error that was outstanding:

```
src/sentry/replays/validators.py:56: error: Argument "choices" to "MultipleChoiceField" has incompatible type "Set[str]"; expected "Sequence[Any]"  [arg-type]
```