ref(py3): Pass id at User init time to fix relation setup in tests
Otherwise you'll end up with the following error:

ValueError: "<User at 0x116018080: id=None>" needs to have a value for field "id" before this many-to-many relationship can be used.