ref: fix test pollution caused by global mocks (#88141)
a couple things here:
- `catch_exceptions=False` hides the actual failure of the click command
-- I put that on all the `invoke(...)` calls so it is easier to debug
(and validate raised exceptions using the standard pytest tooling)
- the actual bug is caused by the (now deleted)
`FakeKeyManagementServiceClient` class having class attributes that are
shared across tests
- I changed the mocking to just mock the class directly -- entirely
avoiding this class of problem

fixes this test pollution:

```console
$ pytest tests/sentry/relocation/tasks/test_process.py::EndToEndTest::test_valid_max_retries tests/sentry/runner/commands/test_backup.py::GoodCompareCommandEncryptionTests::test_compare_decrypt_with_gcp_kms
============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.1.2, pluggy-1.5.0
django: version: 5.1.7
rootdir: /home/asottile/workspace/sentry
configfile: pyproject.toml
plugins: cov-4.0.0, metadata-3.1.1, rerunfailures-15.0, pytest_sentry-0.3.0, django-4.9.0, time-machine-2.16.0, json-report-1.5.0, xdist-3.0.2, fail-slow-0.3.0, anyio-3.7.1
collected 2 items                                                              

tests/sentry/relocation/tasks/test_process.py .                          [ 50%]
tests/sentry/runner/commands/test_backup.py F                            [100%]

=================================== FAILURES ===================================
_____ GoodCompareCommandEncryptionTests.test_compare_decrypt_with_gcp_kms ______
tests/sentry/runner/commands/test_backup.py:258: in test_compare_decrypt_with_gcp_kms
    assert rv.exit_code == 0, rv.output
E   AssertionError: 
E   assert 1 == 0
E    +  where 1 = <Result StopIteration()>.exit_code
=========================== short test summary info ============================
FAILED tests/sentry/runner/commands/test_backup.py::GoodCompareCommandEncryptionTests::test_compare_decrypt_with_gcp_kms - AssertionError: 
========================= 1 failed, 1 passed in 11.35s =========================
```

<!-- Describe your PR here. -->