fix(migration): handle use_case_id integrity error (#49491)
**context**
original migration added in
https://github.com/getsentry/sentry/pull/47940 and has been run in saas.
However when testing out some stuff in s4s we ran into issues running
the migration:

```
django.db.utils.IntegrityError: UniqueViolation('duplicate key value violates unique constraint "perf_unique_org_string_usecase"
DETAIL:  Key (string, organization_id, use_case_id)=(resource_exhausted, 1, transactions) already exists.
')```

This should fix the migration for ST and doesn't need to be rerun for saas since we didn't see any problems in there (we think maybe there is more old data in ST, need to confirm if the celery task that deletes indexer records runs in ST)