ref: avoid mutating os.environ as init cli side-effect (#88223)
fixes this test pollution:

```console
$ pytest tests/sentry/runner/commands/test_init.py::InitTest::test_simple $(tail -1 testlist2)
============================= test session starts ==============================
platform darwin -- Python 3.13.1, pytest-8.1.2, pluggy-1.5.0
django: version: 5.1.7
rootdir: /Users/asottile/workspace/sentry
configfile: pyproject.toml
plugins: fail-slow-0.3.0, time-machine-2.16.0, json-report-1.5.0, metadata-3.1.1, xdist-3.0.2, django-4.9.0, pytest_sentry-0.3.0, anyio-3.7.1, rerunfailures-15.0, cov-4.0.0
collected 2 items                                                              

tests/sentry/runner/commands/test_init.py .                              [ 50%]
tests/sentry/test_wsgi.py F                                              [100%]

=================================== FAILURES ===================================
________________________________ test_wsgi_init ________________________________
tests/sentry/test_wsgi.py:25: in test_wsgi_init
    subprocess.check_call(
../../.local/share/sentry-devenv/pythons/3.13.1/python/lib/python3.13/subprocess.py:419: in check_call
    raise CalledProcessError(retcode, cmd)
E   subprocess.CalledProcessError: Command '['/Users/asottile/workspace/sentry/.venv/bin/python3', '-c', '\nimport sys\nassert "sentry.conf.urls" not in sys.modules\n\nimport sentry.wsgi\nassert "sentry.conf.urls" in sys.modules\n\nimport django.urls.resolvers\nfrom django.conf import settings\nresolver = django.urls.resolvers.get_resolver()\nassert resolver._populated is True\nfor lang, _ in settings.LANGUAGES:\n    assert lang in resolver._reverse_dict\n']' returned non-zero exit status 1.
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "<string>", line 5, in <module>
    import sentry.wsgi
  File "/Users/asottile/workspace/sentry/src/sentry/wsgi.py", line 16, in <module>
    configure()
    ~~~~~~~~~^^
  File "/Users/asottile/workspace/sentry/src/sentry/runner/__init__.py", line 33, in configure
    _configure(ctx, py, yaml, skip_service_validation)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/asottile/workspace/sentry/src/sentry/runner/settings.py", line 101, in configure
    raise ValueError("Configuration file does not exist at '%s'" % click.format_filename(yaml))
ValueError: Configuration file does not exist at 'config/config.yml'
=========================== short test summary info ============================
FAILED tests/sentry/test_wsgi.py::test_wsgi_init - subprocess.CalledProcessError: Command '['/Users/asottile/workspace/sentry/...
========================= 1 failed, 1 passed in 4.53s ==========================
```

<!-- Describe your PR here. -->