ref: implement missing to_query_string for AggregateFilter (#87091)
new test previously failed with:

```
______ ParseSearchQueryBackendTest.test_paren_expression_to_query_string _______
tests/sentry/api/test_event_search.py:304: in test_paren_expression_to_query_string
    assert val.to_query_string() == '(has:1 random():<5)'
src/sentry/api/event_search.py:381: in to_query_string
    children += f" {child.to_query_string()}"
E   AttributeError: 'AggregateFilter' object has no attribute 'to_query_string'
```

<!-- Describe your PR here. -->