feat(projectconfig): Limit experimental config build times (#66949)
Set a 15s time limit on experimental feature computation in project
configs.

For considered alternatives, see
https://github.com/getsentry/team-ingest/issues/286#issuecomment-1988053152.

Notes:
- All features have the default timeout of 15s. Allowing custom timeouts
per feature makes working around them easy with a wrong perception of
timeouts being properly applied.
- 15s is half the time the project config build task is allowed to run.
I expect this limit to hit hardly ever, having little to no impact on
the current state in prod, but allowing us to collect data and tune it
in the future (see https://github.com/getsentry/team-ingest/issues/285).

### mypy errors

When the function provided to `add_experimental_config` doesn't provide
an initial argument for the timeout, mypy errors with the following
(example) message:
```txt
src/sentry/relay/config/__init__.py:444: error: Argument 3 to "add_experimental_config" has incompatible type "Callable[[Project], Mapping[str, Any] | None]"; expected "ExperimentalConfigBuilder"  [arg-type]
```