Python 3: bytes can only contain ASCII literal chars
__SyntaxError: bytes can only contain ASCII literal characters.__ in Python 3 as detected via #14906

The comment says we will use a raw string but the code uses a bytes string.  This PR proposes using an r"string" instead of a b"string".