Fix bug: check_all expects an iterable.
Otherwise you may get a:

    [2015-07-22 21:09:53 +0000] [20813] [ERROR] Error handling request
    Traceback (most recent call last):
      .... lots of stuff ...
      File "sentry/templatetags/sentry_status.py", line 12, in show_system_status
	problems = status_checks.check_all()
      File "sentry/status_checks/__init__.py", line 16, in check_all
	problems.extend(cls().check())
    TypeError: 'NoneType' object is not iterable