ref: inline SENTRY_ANALYTICS_ALIASES to remove import cycle (#70036)
this setting is not overridden in any environment and has not changed
since introduction

resolves this cycle with latest `django-stubs`:

```
src/sentry/analytics/utils.py:13: error: Import cycle from Django settings module prevents type inference for 'SENTRY_ANALYTICS_ALIASES'  [misc]
```

<!-- Describe your PR here. -->