eventerror: don't explode on missing keys while formatting
This helps as messages evolve over time. Previous events will be stored
without keys that are needed if the message in turn, now expects it.
This allows things to gracefully roll forward.