ref: prevent invalid BitField alters (#62199)
example failures:

```
ValueError: migration `0586_add_has_feedbacks_flag` alters a BitField in an unsafe way!

the following flags were added between old flags: has_feedbacks

new flags must be added at the end or flags will change meaning
```

```
ValueError: migration `0620_add_has_new_feedbacks_flag` alters a BitField in an unsafe way!

the following flags were added between old flags: has_new_feedbacks

new flags must be added at the end or flags will change meaning
```

```
ValueError: migration `0625_wat2` alters a BitField in an unsafe way!

the following flags were removed: has_transactions

unused flags must remain to preserve padding for future flags
```

```
ValueError: migration `0625_wat3` alters a BitField in an unsafe way!

the following old flags were reordered:

--- old
+++ new
@@ -3,8 +3,8 @@
 has_transactions
 has_alert_filters
 has_sessions
+has_replays
 has_profiles
-has_replays
 has_feedbacks
 has_new_feedbacks
 spike_protection_error_currently_active

flags must retain historical order or flags will change meaning
```