fix(uptime): Add missing migration dependency (#99825)
Since we're using the Detector model we need a dependency on the
workflow engine.

Without it we get errors like this while trying to run the migration

```
LookupError: No installed app with label 'workflow_engine'.
```