fix(default_cache): Move is_default_cache to options so that ServiceDelegator can be used (#44740)
`ServiceDelegator`'s constructor does not accept additional keyword
arguments and therefore it's failing when `default_cache` is configured
to use it.

```
  File "/usr/src/sentry/src/sentry/attachments/redis.py", line 5, in <module>
    from sentry.cache.redis import RbCache, RedisClusterCache
  File "/usr/src/sentry/src/sentry/cache/__init__.py", line 11, in <module>
    default_cache = import_string(settings.SENTRY_CACHE)(
TypeError: __init__() got an unexpected keyword argument 'is_default_cache'
```