feat(migrations): Add automated checks to migrations, and other safety features. (#25802)
This pr  incorporates https://github.com/tbicr/django-pg-zero-downtime-migrations
into our codebase. I was intending to write most of this functionality, but found that this
library does most of what we need already. Now that we're on Django 2.2 we can finally make 
use of this.

I've added a wrapper around this so that we can decide where it will be applied. Since some of our
legacy migrations fail these checks, I just want to skip them. For new migrations I've made 
`CheckedMigration` the base class in our migration template to guarantee things run safely.

The library itself does a few things:
 - Raises errors for some clearly dangerous situations (renaming tables/columns, adding not null
   columns with/without defaults, changing column types)
 - Automatically wraps all potentially locking operations with `lock_timeout` in postgres, which
   means that if we do block on attempting to apply DDL to a table we won't take down Sentry.
   Instead, the migration will just fail to run. I have set this value to 5s in sentry for now, but we 
   can override it in getsentry as needed.
 - Also wraps most commands with `statement_timeout` for similar reasons. This limits the amount of
   time we allow a migration to run for. We might need to tinker with this a bit to make sure we
   allow some data migrations to be a little long running, and also to allow ops to run them manually.
   This has also been set to 5s, but we can override it in getsentry as needed.
 - Rewrites the way some DDL is generated to run in a safer way. One example is that when we want
    to mark a column as NOT NULL it will instead use the safer method:
     - `ALTER TABLE mytable ADD CONSTRAINT mytable_myfield_constraint CHECK (mytable_myfield_constraint IS NOT NULL) NOT VALID`
     - `ALTER TABLE mytable VALIDATE CONSTRAINT mytable_myfield_constraint`

I've also imported and modified a portion of the tests from the library to verify against our 
integration. I added missing tests here too and uncovered that they weren't successfully guarding
against renaming a table, so I've added that into our base class.

Some example ddl it generates:

 - Creating a new table
```
CREATE TABLE "sentry_testmodel" ("id" bigserial NOT NULL PRIMARY KEY, "field" integer NOT NULL);
```
 - Creating a new table with an FK. Note that it's smart enough to set statement and lock timeouts here 
    when adding the constraint, which it then validates after. It also knows to create indexes concurrently
    by default to avoid locks.
```
CREATE TABLE "sentry_testmodel" ("id" bigserial NOT NULL PRIMARY KEY, "field" integer NOT NULL, "organization_id" bigint NOT NULL);
SET statement_timeout TO '5s';
SET lock_timeout TO '5s';
ALTER TABLE "sentry_testmodel" ADD CONSTRAINT "sentry_testmodel_organization_id_0bc43b70_fk_sentry_or" FOREIGN KEY ("organization_id") REFERENCES "sentry_organization" ("id") DEFERRABLE INITIALLY DEFERRED NOT VALID;
SET statement_timeout TO '0ms';
SET lock_timeout TO '0ms';
ALTER TABLE "sentry_testmodel" VALIDATE CONSTRAINT "sentry_testmodel_organization_id_0bc43b70_fk_sentry_or";
CREATE INDEX CONCURRENTLY "sentry_testmodel_organization_id_0bc43b70" ON "sentry_testmodel" ("organization_id");
```
 - Adding a non-null column with a default
```
<Snipped stack trace>
  File "/Users/dan/code/sentry/src/sentry/db/postgres/schema.py", line 65, in inner
    raise UnsafeOperationException(exc_str.format(*formatted_args))
django_zero_downtime_migrations.backends.postgres.schema.UnsafeOperationException: Adding TestModel.new_non_null as column with a default is unsafe.
More info: https://develop.sentry.dev/database-migrations/#adding-columns-with-a-default
```


Finally, this pr looks really large, but 70% of it is tests and migrations relating to them. The code 
involved isn't too complicated.