chore(eslint): Don't specify the .eslintrc.* file in vscode workspace settings (#33308)
I saw an error in the `vscode-eslint` plugin:
```
Error: Invalid Options:
- Unknown options: configFile
- 'configFile' has been removed. Please use the 'overrideConfigFile' option instead.
```

The plugin can find our eslintrc file without the explicit `configFile` field because the file sticks to the normal naming convention.