ref: add healthcheck for snuba starting
I was able to reproduce tests starting too quickly for snuba startup via this:

```
docker rm -f sentry_snuba && sentry devservices up && NEED_SNUBA=true python3 -m tools.devservices_healthcheck && pytest tests/sentry_plugins/amazon_sqs/test_plugin.py -k test_message_group_error
```

when this failed it failed like:

```
    raise snuba.SnubaError(err)
E   sentry.utils.snuba.SnubaError: HTTPConnectionPool(host='127.0.0.1', port=1218): Max retries exceeded with url: /tests/events/eventstream (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
=========================== short test summary info ============================
FAILED tests/sentry_plugins/amazon_sqs/test_plugin.py::AmazonSQSPluginTest::test_message_group_error - sentry.utils.snuba.SnubaError: HTTPConnectionPool(host='127.0.0.1', port=12...

```

this is in line with the failures we see in the flaky tests dashboard:

https://sentry.sentry.io/issues/4313267447/?project=2423079&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=24h&stream_index=4