ref: fix usage_accountant-related test pollution (#88113)
previously failing with:

```console
$ pytest tests/sentry/ingest/ingest_consumer/test_ingest_consumer_processing.py::test_accountant_transaction tests/sentry/usage_accountant/test_accountant.py::test_accountant
============================= test session starts ==============================
platform darwin -- Python 3.13.1, pytest-8.1.2, pluggy-1.5.0
django: version: 5.1.7
rootdir: /Users/asottile/workspace/sentry
configfile: pyproject.toml
plugins: fail-slow-0.3.0, time-machine-2.16.0, json-report-1.5.0, metadata-3.1.1, xdist-3.0.2, django-4.9.0, pytest_sentry-0.3.0, anyio-3.7.1, rerunfailures-15.0, cov-4.0.0
collected 2 items                                                              

tests/sentry/ingest/ingest_consumer/test_ingest_consumer_processing.py . [ 50%]
                                                                         [ 50%]
tests/sentry/usage_accountant/test_accountant.py F                       [100%]

=================================== FAILURES ===================================
_______________________________ test_accountant ________________________________
tests/sentry/usage_accountant/test_accountant.py:47: in test_accountant
    accountant.init_backend(producer)
src/sentry/usage_accountant/accountant.py:33: in init_backend
    assert _accountant_backend is None, "Accountant already initialized once."
E   AssertionError: Accountant already initialized once.
=========================== short test summary info ============================
FAILED tests/sentry/usage_accountant/test_accountant.py::test_accountant - AssertionError: Accountant already initialized once.
========================= 1 failed, 1 passed in 5.12s ==========================
```

<!-- Describe your PR here. -->