fix(integrations): Fix sending requests locally (#56303)
Since https://github.com/getsentry/sentry/pull/53836/files was merged we
haven't been able to develop integrations locally because of this error
`AttributeError: 'NoneType' object has no attribute 'setdefault'` since
`proxies` is set to `None` rather than an empty dict.