fix(sdk-loader): Prevent infinite recursion when calling `Sentry.configureScope()` (#122821)
The `Sentry.configureScope` API was removed in version 8.0.0 of the JS
SDK. Unfortunately, the removal never trickled down to the loader, which
still treated the API as a queuable SDK API.

This meant that an application using the loader and calling
`Sentry.configureScope()` would enqueue this call, later to be replayed
when the actual SDK bundle was loaded. Because the SDK bundle no longer
contained `configureScope`, the `globalThis.Sentry.configureScope`
property would not be overwritten. Thus once it was replayed, the call
would enqueue another `configureScope` call into the queue, slowly
building up memory in the queue.

This led to out of memory crashes in browsers. I could reproduce this
with this simple setup:

```html
<head>
    <script
      src="_loader_bundle_url_"
      crossorigin="anonymous"
    ></script>

    <script>
      Sentry.configureScope(function () {});
    </script>
</head>
```

Admittedly an edge case because this API isn't documented since years
but we believe one customer is running into this issue, so definitely
worth fixing.

### Implications of this change

If users call `Sentry.configureScope` after this change, a type error
will be thrown:

> TypeError: Sentry.configureScope is not a function

Which is exactly the behaviour today for any other non-queueable
operations as long as the SDK isn't loaded. I think this is acceptable
given the API doesn't exist since >2 years but if reviewers prefer, we
could
- guard queued function invocations and fail silently (probably a
worthwhile change either way but should be a separate PR I think). Only
catches calls while replaying the queue though.
- export a no-op shim from the loader script directly. Fails silently
for all calls, regardless of SDK loading state
- or add a shim to SDK bundles (in which case, we need to cut a v8, v9
and v10 release with the shim before merging this PR) (hard but somewhat
precedented)