fix(performance): Use existing type narrowing on node string
fixes a type error in react 18 when an object type might be rendered

```
Error: static/app/views/performance/newTraceDetails/traceDrawer/traceDrawer.tsx(382,20): error TS2322: Type 'string | TraceTreeNode<NodeValue>' is not assignable to type 'ReactNode'.
  Type 'TraceTreeNode<NodeValue>' is not assignable to type 'ReactNode'.
    Type 'TraceTreeNode<NodeValue>' is missing the following properties from type 'ReactPortal': type, props, key
```