ref: improve release serializer where Release.authors is None (#93366)
mypy helpfully points out the bug here:

```
src/sentry/api/serializers/models/release.py:129: error: Argument 1 to "update" of "set" has incompatible type "list[str] | None"; expected "Iterable[Any]"  [arg-type]
src/sentry/api/serializers/models/release.py:151: error: Item "None" of "list[str] | None" has no attribute "__iter__" (not iterable)  [union-attr]
```

resolves SENTRY-3ZWS

<!-- Describe your PR here. -->