ref(heroku): Handle null slug (#44971)
Handle the case where `slug` is null which is causing an AttributeError
`'NoneType' object has no attribute 'get'` on the chained `.get()`. I'm
not sure if Heroku sends differently shaped payloads in certain cases,
but usually the commit data is in `data["slug"]["commit"]`.

Fixes [SENTRY-YPR](https://sentry.sentry.io/issues/3920357271/), also
see [this issue](https://getsentry.atlassian.net/browse/ISSUE-1646)