ref: Add safety parameter to `db.delete_column`.
Deleting columns in production is dangerous. Since we do a rolling deploy, once the column is
deleted we have some percent of servers running code that expects the column to still exist in the
database. Our pattern for working around this is to remove the column from the model and make the
column nullable if not currently. Then once this has deployed successfully, it's safe to remove the
column from the table.

This is currently enforced by making sure the right person checks it, but is easy to miss. So this
PR adds a safety lock parameter to remind anyone who is deleting a column to go through this
procedure. Produces an error message like:

```
 > sentry:0474_auto__del_field_sentryappinstallation_authorization
Error in migration: sentry:0474_auto__del_field_sentryappinstallation_authorization
Traceback (most recent call last):
  File "/Users/dfuller/.virtualenvs/sentry/bin/sentry", line 11, in <module>
    load_entry_point('sentry', 'console_scripts', 'sentry')()
  File "/Users/dfuller/code/sentry/src/sentry/runner/__init__.py", line 162, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dfuller/code/sentry/src/sentry/runner/decorators.py", line 36, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dfuller/code/sentry/src/sentry/runner/commands/upgrade.py", line 75, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair)
  File "/Users/dfuller/code/sentry/src/sentry/runner/commands/upgrade.py", line 30, in _upgrade
    ignore_ghost_migrations=True,
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/Users/dfuller/code/sentry/src/south/management/commands/syncdb.py", line 125, in handle_noargs
    management.call_command('south_migrate', **options)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/dfuller/.virtualenvs/sentry/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/dfuller/code/sentry/src/south/management/commands/south_migrate.py", line 105, in handle
    ignore_ghosts=ignore_ghosts,
  File "/Users/dfuller/code/sentry/src/south/migration/__init__.py", line 231, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/Users/dfuller/code/sentry/src/south/migration/migrators.py", line 290, in migrate_many
    result = self.migrate(migration, database)
  File "/Users/dfuller/code/sentry/src/south/migration/migrators.py", line 131, in migrate
    result = self.run(migration, database)
  File "/Users/dfuller/code/sentry/src/south/migration/migrators.py", line 240, in run
    return super(Forwards, self).run(migration, database)
  File "/Users/dfuller/code/sentry/src/south/migration/migrators.py", line 113, in run
    return self.run_migration(migration, database)
  File "/Users/dfuller/code/sentry/src/south/migration/migrators.py", line 85, in run_migration
    migration_function()
  File "/Users/dfuller/code/sentry/src/south/migration/migrators.py", line 61, in <lambda>
    return (lambda: direction(orm))
  File "/Users/dfuller/code/sentry/src/sentry/south_migrations/0474_auto__del_field_sentryappinstallation_authorization.py", line 16, in forwards
    db.delete_column(u'sentry_sentryappinstallation', 'authorization_id')
  File "/Users/dfuller/code/sentry/src/south/db/generic.py", line 60, in _column_rm
    return func(self, table, column, *args, **opts)
  File "/Users/dfuller/code/sentry/src/south/db/generic.py", line 948, in delete_column
    'Deleting columns is dangerous. You need to do this in two '
Exception: Deleting columns is dangerous. You need to do this in two separate commits that must be deployed separately:
 - Remove the column from the django model, and make it nullable in the table if it currently is not.
 - After the previous step has deployed, write the migration to remove the column from the table itself, and set `safety_lock` to False.
If unsure, ask in #engineering.
```