fix(preprod): correctly attribute rate limiting errors (#106580)
Ultimately doesn't change any behavior since we were still retrying off
the old error type, but should let us better attribute how often rate
limiting is happening. In our backend logs you can see these come back
as 403 which triggers some ApiForbidden error logic in our base
integrations code:

```
File "/usr/src/sentry/src/sentry/shared_integrations/client/base.py", line 280, in _request
    raise ApiError.from_response(error_resp, url=full_url) from e
sentry.shared_integrations.exceptions.ApiForbiddenError: {"message":"API rate limit exceeded for installation ID XXX. If you reach out to GitHub Support for help, please include the request ID XXXX and timestamp XXXX UTC. For more on scraping GitHub and how it may affect your rights, please review our Terms of Service (https://docs.github.com/en/site-policy/github-terms/github-terms-of-service)","documentation_url":"https://docs.github.com/rest/overview/rate-limits-for-the-rest-api","status":"403"}"
```

---------

Co-authored-by: getsantry[bot] <66042841+getsantry[bot]@users.noreply.github.com>