chore:(eslint) Don't specify the .eslintrc.* file in vscode workspace settings
I saw seeing an error in the `vscode-eslint` plugin that:
```
Error: Invalid Options:
- Unknown options: configFile
- 'configFile' has been removed. Please use the 'overrideConfigFile' option instead.
```