ref: fix test pollution in seer test_grouping_records (#89043)
previously failing with:

```console
$ pytest tests/sentry/seer/similarity/test_grouping_records.py::test_post_bulk_grouping_records_use_reranking tests/sentry/seer/similarity/test_grouping_records.py::test_post_bulk_grouping_records_failure
============================= test session starts ==============================
platform darwin -- Python 3.13.1, pytest-8.1.2, pluggy-1.5.0
django: version: 5.1.7
rootdir: /Users/asottile/workspace/sentry
configfile: pyproject.toml
plugins: fail-slow-0.3.0, repeat-0.9.3, time-machine-2.16.0, json-report-1.5.0, metadata-3.1.1, xdist-3.0.2, django-4.9.0, pytest_sentry-0.3.0, anyio-3.7.1, rerunfailures-15.0, cov-4.0.0
collected 2 items                                                              

tests/sentry/seer/similarity/test_grouping_records.py .F                 [100%]

=================================== FAILURES ===================================
___________________ test_post_bulk_grouping_records_failure ____________________
tests/sentry/seer/similarity/test_grouping_records.py:105: in test_post_bulk_grouping_records_failure
    mock_logger.info.assert_called_with(
../../.local/share/sentry-devenv/pythons/3.13.1/python/lib/python3.13/unittest/mock.py:977: in assert_called_with
    raise AssertionError(_error_message()) from cause
E   AssertionError: expected call not found.
E   Expected: info('seer.post_bulk_grouping_records.failure', extra={'group_ids': '[1,2]', 'project_id': 1, 'reason': 'INTERNAL SERVER ERROR', 'stacktrace_length_sum': 24, 'use_reranking': False})
E     Actual: info('seer.post_bulk_grouping_records.failure', extra={'group_ids': '[1,2]', 'project_id': 1, 'stacktrace_length_sum': 24, 'use_reranking': True, 'reason': 'INTERNAL SERVER ERROR'})
=========================== short test summary info ============================
FAILED tests/sentry/seer/similarity/test_grouping_records.py::test_post_bulk_grouping_records_failure - AssertionError: expected call not found.
========================= 1 failed, 1 passed in 4.59s ==========================
```

<!-- Describe your PR here. -->