fix(replay): Fix useProjectSdkNeedsUpdate to cache 500 results, and not refetch each time the data is needed (#60849)
The problem was that a parent and child components were both making
requests to the `/sdk-updates/` endpoint.
- When the parent makes the request, we get all the `isLoading:true,
isError: false, data:undefined` state back from useQuery
- Eventually a 500 is returned. This is not put into the queryCache by
useQuery
- The parent will take that 500 error, and render the child component,
which is fine.
- The child component also needs to fetch `/sdk-updates/`, which resets
the `isLoading, isError` state
    - The state is reset for both the child and the parent!
- The parent is now re-rendering, because the query state is shared, so
we get into this infinite loop of re-fetches
- The re-fetch loop continues, and nothing is rendered in the mean time
because nothing is in the cache, while the loop is running all we know
is we're waiting for a successful response.