fix: check for URIError instead of URI malformed error message (#97663)
Checking for `err.message === 'URI malformed'` is brittle because:

1. Messages can differ per browser, [according to
MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI):

```
URIError: URI malformed (V8-based)
URIError: malformed URI sequence (Firefox)
URIError: String contained an illegal UTF-16 sequence. (Safari)
```

2. The current code only compiles because `err` is implicitly `any`;
When switching to `unknown`, it will error because `message` might not
exist.

---

Switching to an `err instanceof URIError` check should fix both
problems.

/edit: apparently, this has been fixed in ReactRouter v5, so we
shouldn’t even hit this path:

- https://github.com/remix-run/history/pull/656