ref: remove tools.hack_pip (#79555)
- this has been "broken" since end of july (when pip 24.2 released)
- it's unclear when the underlying problem was fixed (if it was?)
- I suspect github might have improved their networking? or gcp?
- we haven't seen ReadTimeout errors though so presumably something in
pip changed to resolve this
- we can always bring this back later with the correct `retry` decorator
-- but it's simpler to just remove this!

```
working around https://github.com/pypa/pip/issues/12383#issuecomment-1808598097
writing: /home/runner/work/sentry/sentry/.venv/lib/python3.12/site-packages/sentry-pip-hack.pth
Error processing line 1 of /home/runner/work/sentry/sentry/.venv/lib/python3.12/site-packages/sentry-pip-hack.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 206, in addpackage
    File "<string>", line 1, in <module>
    File "<string>", line 2, in <module>
  ModuleNotFoundError: No module named 'pip._vendor.tenacity'

Remainder of file ignored
```

getsentry first: https://github.com/getsentry/getsentry/pull/15456

<!-- Describe your PR here. -->