ref: ignore all of google.* third party namespaces (#70165)
due to the way google's namespace package is set up it sometimes thinks
some of the modules exist and produces bogus errors

fixes spurious:
```
src/sentry/analytics/pubsub.py:8: error: Module "google.cloud" has no attribute "pubsub_v1"  [attr-defined]
```

<!-- Describe your PR here. -->