fix(migrations): Get migrations table back in-sync (#91739)
We had a partially applied migration in 082153572e7, it's applied in
S4S, DE, and marked as applied in US, but did not actually create the
column.

This migration is just intended to get the django_migrations table in
sync across regions. Later we'll write a sql migration that get's the
tables in sync, and after that we can write our state migration.

---

Full context

Here was the failure
```
django.db.utils.OperationalError: QueryCanceled('canceling statement due to statement timeout\n')
SQL: ALTER TABLE "sentry_monitorcheckin" ADD COLUMN "date_in_progress" timestamp with time zone NULL
  Applying monitors.0003_record_date_in_progress...Container sentry terminated due to reason Error.
```

However looking at the migrations table in US I see:

```sql
SELECT
  *
FROM
  django_migrations
where
  app = 'monitors'
  and name = '0003_record_date_in_progress'
```

I see that django thinks it was appleid, however the column definitely
is not there

```sql
SELECT 
  table_schema,
  table_name,
  column_name,
  data_type
FROM 
  information_schema.columns
WHERE 
  table_name = 'sentry_monitorcheckin'
  AND column_name = 'date_in_progress';
```

This migration was reverted, so it was never applied in other regions.