fix(replay): Fix error breadcrumb not in Chapter
It looks like we are losing millisecond precision w/ the start timestamp and/or duration if the error is the last event we receive in the replay.

Take a look at [this replay](https://sentry.sentry.io/explore/replays/6037de22e46640159865493446790405/?project=11276&query=count_errors%3A%3E0&referrer=%2Fexplore%2Freplays%2F&statsPeriod=7d&t_main=ai&yAxis=count%28%29) for an example. `getChapterFrames()` trims to between start + end and error occurs 718ms later:

Start TS: 1754421644000
Duration: 246000
End TS: 1754421890000
Error: 1754421890718 (+718ms)

The proposed solution creates a new getter that does not trim frames since we use the chapter timestamps to trim anyway.