ref: fix test pollution in api.bases.test_group (#88839)
the hardcoded user id would collide with any test running before it
causing the test to fail

example test pollution before fixing:

```console
$ pytest tests/integration/test_api.py::AuthenticationTest::test_sso_redirect_url_external_removed $(tail -1 hmmm)
============================= test session starts ==============================
platform darwin -- Python 3.13.1, pytest-8.1.2, pluggy-1.5.0
django: version: 5.1.7
rootdir: /Users/asottile/workspace/sentry
configfile: pyproject.toml
plugins: fail-slow-0.3.0, repeat-0.9.3, time-machine-2.16.0, json-report-1.5.0, metadata-3.1.1, xdist-3.0.2, django-4.9.0, pytest_sentry-0.3.0, anyio-3.7.1, rerunfailures-15.0, cov-4.0.0
collected 2 items                                                              

tests/integration/test_api.py .                                          [ 50%]
tests/sentry/api/bases/test_group.py F                                   [100%]

=================================== FAILURES ===================================
___________ GroupAiPermissionTest.test_demo_user_demo_mode_disabled ____________
tests/sentry/api/bases/test_group.py:46: in test_demo_user_demo_mode_disabled
    demo_user = self.create_user(id=DEMO_USER_ID)
src/sentry/testutils/fixtures.py:278: in create_user
    return Factories.create_user(*args, **kwargs)
../../.local/share/sentry-devenv/pythons/3.13.1/python/lib/python3.13/contextlib.py:85: in inner
    return func(*args, **kwds)
src/sentry/testutils/factories.py:923: in create_user
    assert UserEmail.objects.filter(user=user, email=email).update(is_verified=True)
E   AssertionError: assert 0
E    +  where 0 = <bound method BaseQuerySet.update of <BaseQuerySet []>>(is_verified=True)
E    +    where <bound method BaseQuerySet.update of <BaseQuerySet []>> = <BaseQuerySet []>.update
E    +      where <BaseQuerySet []> = <bound method QuerySet.filter of <sentry.db.models.manager.base.UserEmailManager object at 0x118377380>>(user=<User at 0x159617e30: id=2>, email='7ae013e303f3455c8d0e13c83735eedb@example.com')
E    +        where <bound method QuerySet.filter of <sentry.db.models.manager.base.UserEmailManager object at 0x118377380>> = <sentry.db.models.manager.base.UserEmailManager object at 0x118377380>.filter
E    +          where <sentry.db.models.manager.base.UserEmailManager object at 0x118377380> = UserEmail.objects
=========================== short test summary info ============================
FAILED tests/sentry/api/bases/test_group.py::GroupAiPermissionTest::test_demo_user_demo_mode_disabled - AssertionError: assert 0
========================= 1 failed, 1 passed in 6.12s ==========================
%4|1743794058.198|TERMINATE|rdkafka#producer-1| [thrd:app]: Producer terminating with 1 message (211 bytes) still in queue or transit: use flush() to wait for outstanding message delivery

```

<!-- Describe your PR here. -->