fix(snuba): add missing api.metrics.totals.second_query to Referrer enum (#104155)
Fixing this particular issue:

```
Traceback (most recent call last):
  File "/usr/src/sentry/src/sentry/snuba/referrer.py", line 964, in validate_referrer
    raise Exception(error_message)
Exception: referrer api.metrics.totals.second_query is not part of Referrer Enum
```

Closes
https://linear.app/getsentry/issue/TET-1522/snuba-queries-raising-warning