devenv: allow for python 3.8, and prepare CI configuration for dual 3.6/3.8 (#29058)
People can now set `SENTRY_PYTHON_VERSION=3.8.12` in their `.env`, and follow what direnv has to say in order to set up a new 3.8 venv. For example if I have a 3.6.10 venv and do direnv allow:

```
ERROR: You have explicitly set a non-recommended Python version (3.8.10),
but it doesn't match the value of python's version: 3.6.13
You should create a new 3.8.10 virtualenv by running  "rm -rf .venv && direnv allow".
```

Then, we'll build+install 3.8.10 if we don't have it already, and finish bootstrapping the new venv.

I'm gonna follow up with getsentry, and then after that, a PR that adds required tests on 3.8 in addition to 3.6, and sending out a mail on how to move devenv to 3.8. It'll be pretty expensive, but we need to ensure dual compatibility during this transitional period. I won't merge that PR until a full 3.8 deploy is initiated, and after things look good I'll put up a PR to remove 3.6 entirely from devenv and tests.