Tests that do not require DB complain about `symbolicator.options` missing
You can raise an exception inside of `sentry.options.store.py:get_store` (e.g. `raise Exception("foo")`) in order to show what is the real code path that triggers the issue.

This is the output when raising an error within `get_store`:
```
pytest -s -vvv tests/test_foo.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/utils/pytest/sentry.py", line 223, in pytest_configure
INTERNALERROR>     initialize_app({"settings": settings, "options": None})
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/runner/initializer.py", line 379, in initialize_app
INTERNALERROR>     register_plugins(settings)
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/runner/initializer.py", line 49, in register_plugins
INTERNALERROR>     init_plugin(plugin)
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/runner/initializer.py", line 77, in init_plugin
INTERNALERROR>     plugin.setup(bindings)
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry_plugins/github/plugin.py", line 251, in setup
INTERNALERROR>     if self.has_apps_configured():
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry_plugins/github/plugin.py", line 243, in has_apps_configured
INTERNALERROR>     options.get("github.apps-install-url")
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/options/manager.py", line 166, in get
INTERNALERROR>     result = self.store.get(opt, silent=silent)
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/options/store.py", line 104, in get
INTERNALERROR>     result = self.get_store(key, silent=silent)
INTERNALERROR>   File "/Users/armenzg/code/sentry/src/sentry/options/store.py", line 194, in get_store
INTERNALERROR>     raise Exception("foo")
INTERNALERROR> Exception: foo
```

This is the original output:
```
pytest -s -vvv tests/test_foo.py
========================================================================================================== test session starts ==========================================================================================================
platform darwin -- Python 3.8.13, pytest-7.2.1, pluggy-0.13.1 -- /Users/armenzg/code/sentry/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /Users/armenzg/code/sentry, configfile: pyproject.toml
plugins: forked-1.4.0, fail-slow-0.3.0, rerunfailures-11.0, sentry-0.1.11, xdist-3.0.2, cov-4.0.0, django-4.4.0
collected 1 item

tests/test_foo.py::test_math Traceback (most recent call last):
  File "/Users/armenzg/code/sentry/src/sentry/options/store.py", line 195, in get_store
    value = self.model.objects.get(key=key.name).value
  File "/Users/armenzg/code/sentry/src/sentry/db/models/manager/base.py", line 259, in get
    model: M = super().get(*args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/Users/armenzg/code/sentry/src/sentry/db/postgres/decorators.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/Users/armenzg/code/sentry/src/sentry/db/postgres/base.py", line 110, in _cursor
    return super()._cursor()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/Users/armenzg/code/sentry/.venv/lib/python3.8/site-packages/pytest_django/plugin.py", line 714, in _blocking_wrapper
    raise RuntimeError(
RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
13:53:01 [ERROR] sentry: option.failed-lookup (key='symbolicator.options')
```