ref: fix typing for sdk tag normalization (#72529)
callers currently call this with both Event and CanonicalKeyDict which
happens to accidentally work due to the .data property

I'm killing CanonicalKeyDict so I have to fix this first

this also fixes an error in ignored files:

```diff
$ diff -u .artifacts/mypy-all{,.new}
--- .artifacts/mypy-all	2024-06-11 14:59:12
+++ .artifacts/mypy-all.new	2024-06-11 14:57:56
@@ -232,7 +232,6 @@
 src/sentry/grouping/fingerprinting/__init__.py:150: error: Incompatible types in assignment (expression has type "list[dict[str, Any]]", variable has type "None")  [assignment]
 src/sentry/grouping/fingerprinting/__init__.py:153: error: Incompatible return value type (got "None", expected "list[dict[str, str]]")  [return-value]
 src/sentry/grouping/fingerprinting/__init__.py:157: error: Incompatible types in assignment (expression has type "list[dict[str, str]]", variable has type "None")  [assignment]
-src/sentry/grouping/fingerprinting/__init__.py:157: error: Argument 1 to "normalized_sdk_tag_from_event" has incompatible type "dict[str, object]"; expected "Event"  [arg-type]
 src/sentry/grouping/fingerprinting/__init__.py:158: error: Incompatible return value type (got "None", expected "list[dict[str, str]]")  [return-value]
 src/sentry/grouping/fingerprinting/__init__.py:161: error: Incompatible types in assignment (expression has type "list[dict[str, Any]]", variable has type "None")  [assignment]
 src/sentry/grouping/fingerprinting/__init__.py:164: error: Incompatible return value type (got "None", expected "list[dict[str, str]]")  [return-value]
@@ -3889,4 +3888,4 @@
 tests/sentry/api/bases/test_organization.py:87: error: Argument "request" to "has_permission" of "ScopedPermission" has incompatible type "HttpRequest"; expected "Request"  [arg-type]
 tests/sentry/api/bases/test_organization.py:88: error: Argument "request" to "has_object_permission" of "OrganizationPermission" has incompatible type "HttpRequest"; expected "Request"  [arg-type]
 tests/sentry/api/bases/test_organization.py:244: error: Argument "request" to "is_not_2fa_compliant" of "OrganizationPermission" has incompatible type "HttpRequest"; expected "Request"  [arg-type]
-Found 2896 errors in 381 files (checked 5795 source files)
+Found 2895 errors in 381 files (checked 5795 source files)
```

<!-- Describe your PR here. -->

---------

Co-authored-by: Armen Zambrano G. <44410+armenzg@users.noreply.github.com>