ci: Temporarily disable creating images for frontend workflow (#23941)
This morning, the frontend workflow started failing with:

> Error: Failed to launch the browser process!
> /node_modules/puppeteer/.local-chromium/linux-782078/chrome-linux/chrome: error while
  loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

We're going to temporarily disable it until we can investigate what's causing it.