feat(feedback): Update the feedback details ui to highlight messages in purple (#66734)
Re-do of https://github.com/getsentry/sentry/pull/66641 which had some
kind of lint issue

The original PR failed in master on this CI step:
```
Run yarn lint
yarn run v1.22.5
$ yarn lint:biome && yarn lint:prettier && yarn lint:js && yarn lint:css
$ biome check .
Checked 5238 files in 1[9](https://github.com/getsentry/sentry/actions/runs/8239971136/job/22534388761#step:8:10)07ms. No fixes needed.
$ prettier **/*.md **/*.yaml **/*.{ts,tsx} --check
Checking formatting...
[warn] static/app/components/feedback/feedbackItem/useFeedbackActions.ts
[warn] Code style issues found in the above file. Run Prettier to fix.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

---

Matches figma designs:

https://www.figma.com/file/i6GG14NOoRYdSiqDnqqafP/Specs%3A-User-Feedback-v2?type=design&node-id=988-2899&mode=design&t=CYQn8dNlbgZDl5P4-0

| before | after |
| --- | --- |
| <img width="607" alt="before"

src="https://github.com/getsentry/sentry/assets/187460/71630cf3-fed5-47bb-a66e-b9f1130ce54e">
| <img width="603" alt="after"

src="https://github.com/getsentry/sentry/assets/187460/3684a7ac-4e8c-49b4-8ae0-ce4432215b4c">



**Different widths in the app:**
| size | img |
| --- | --- |
| small | <img width="627" alt="small"

src="https://github.com/getsentry/sentry/assets/187460/ba592218-4739-4cfd-b318-fb91f308d524">
|
| medium | <img width="658" alt="medium"

src="https://github.com/getsentry/sentry/assets/187460/fc3c2878-ff1c-47b3-9d74-5c4888e53435">
| large | <img width="841" alt="large"

src="https://github.com/getsentry/sentry/assets/187460/073b2717-0d6c-4d0d-b01e-ed8395d9415f">


Fixes https://github.com/getsentry/sentry/issues/66219

<!-- Describe your PR here. -->