feat(notif-platform): Prototype the template layer (#94369)
This PR introduces some more structure around templates, including a
template registry. I've also added some tests to ensure developer
interface with it correctly.

For example, registering with an unknown key:

```
@template_registry.register('some-unknown-key')
MyTemplate(...): ...
```
will yield:
```
tests/sentry/notifications/platform/test_registry.py:40: in test_no_unknown_registration_keys
    assert (
E   AssertionError: Template <class 'sentry.notifications.platform.registry.DemoNotificationTemplate'> was registered with an unknown key (some-unknown-key)
E
E   assert 'some-unknown-key' in NotificationTemplateKey
```
and forgetting a template, but adding to NotificationTemplateKey

```
tests/sentry/notifications/platform/test_registry.py:55: in test_no_unused_production_keys
    raise AssertionError(
E   AssertionError: Known NotificationTemplateKey(s) have no associated template registered: 'my_new_template'
E   Use @template_registry.register() to register them, or explicitly exclude them within this test.

```

We've discussed this below block offline, it's the way forward for now
so collapsing it for legibility
  <details> 
  <summary>Explanation of NotificationRenderedTemplate</summary>
  
  This has a few things to consider though: 
- For email, we have flexibility, we can just pass the existing django
templates and get whatever level of customization we want by modifying
the templates.
- For integrations though, `body` (for example) is just a `str`. So if a
notification wanted bold the text of a slack message, it'd have to be
signaled within the `str` to bold somehow, likely from a shared
templating language (e.g. markdown `**`s), which is idealistic. This
would have to be understood by all providers; which is reasonable for
MSTeams/Slack/Discord, but might not work for future providers(?) if
they don't parse markdown, or do so differently (e.g notion uses `|
text` for quotes, md uses `> text` even though most other syntax is
md-like)
- If we allow markdown in the `str` attributes, it's likely we'd get
bugs as soon as someone tries a provider specific md formatting (e.g.
imagine like `f"[John](@john)"` or something)
- Onboarding new providers would also become a minefield if there is
syntax assumed to be understood by all that is done differently for
other integrations (e.g. if jira uses [img:link](...) but slack uses
![link](...)) -- If a new provider needs a new format, it means every
notify call must now be updated to include the new syntax :(
  
    
The only way around this I can see is restricting to top level building
blocks (e.g. `subject`, `body`, `action`, `chart`) that explicitly will
not allow custom formatting, and deferring to renderers to do all
non-standard elements. Pros: Consistency out of the box, and devs never
need to learn slack markdown vs discord markdown. Cons: If a dev wants
to bold text, they need a custom renderer for each provider 🙃
  </details>