fix(configoptions): Change from YAML parsing to JSON parsing to fix float parsing issue (#118492)
Numbers less than 0.0001 (1.0e-4) get parsed in scientific notation when
`repr()` is called on them:
<img width="598" height="167" alt="sentry-options git
(kjiangfix-doc-Links) python"
src="https://github.com/user-attachments/assets/8a5a709d-160e-47d9-b70d-8c214be510ee"
/>

YAML 1.1 only parses scientific notation as a float if there is a
decimal point `.`. Otherwise, it is parsed as a string. `configoptions`
assumed that small floats were strings and threw errors that the types
didn't match. This is an issue one of our engineers was running into:

```
Error:  sentry.options_automator:
    Option [OPTION_NAME] has invalid type. got <class 'str'>, expected float
```

I chose to solve this by switching us over to JSON parsing. It was
originally YAML parsing because we hand-wrote YAML, but with our current
automator system, we only write out JSON files. It was working before
because JSON is a subset of YAML.

The majority of the diff is updating test fixtures. The actual change is
just one line. I've confirmed that there are no other live files writing
YAML, but included a fallback just in case.