Use correct variable name for package path
s/package_path/pkg_path/ in `build_assets.py`

Was causing this error when installing Sentry 8.9.0:

```
  File "/www/sentry/build/sentry/src/sentry/utils/distutils/commands/build_assets.py", line 98, in _needs_built

    version_info = self._get_package_version()

  File "/www/sentry/build/sentry/src/sentry/utils/distutils/commands/build_assets.py", line 73, in _get_package_version

    self.package_path,

  File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__

    raise AttributeError, attr

AttributeError: package_path
```