chore: import getsentry override reqs (#60034)
context:

* https://github.com/getsentry/sentry/pull/60009

```
Anton Pirker
  [2 days ago](https://sentry.slack.com/archives/CUHS29QJ0/p1699876762219409)
Can someone help me bump the Sentry Python SDK version in sentry and getsentry?
I have a [PR for bumping the SDK in ](https://github.com/getsentry/sentry/pull/59837)sentry but it fails because there is an error in the getsentry tests:
ERROR: Cannot install sentry-sdk 1.31.0 (from https://github.com/getsentry/sentry-python/archive/1b445c61d1e263ccd04d823307b3a03a6945dc8a.zip) and sentry-sdk==1.35.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested sentry-sdk 1.31.0 (from https://github.com/getsentry/sentry-python/archive/1b445c61d1e263ccd04d823307b3a03a6945dc8a.zip)
    The user requested sentry-sdk==1.35.0
So I created a [PR in ](https://github.com/getsentry/getsentry/pull/12056)getsentry to get rid of 1b445c61d1e263ccd04d823307b3a03a6945dc8a.zip (because the code is now in the new python sdk that is released publicly). I called bin/bump-sentry --no-skip fb0547a8588bd4f095d3151b43d952019fd9b4a0 in getsentry (with the SHA being the one from my branch in sentry. But the PR has a conflict in the file sentry-version (where my SHA from bin/bump-sentry is).
In what order do I need to do things so all the checks pass?

Anthony Sottile
  [3 hours ago](https://sentry.slack.com/archives/CUHS29QJ0/p1700065627109659?thread_ts=1699876762.219409&cid=CUHS29QJ0)
yeah I think that this isn't going to work without refactoring the dependency setup -- I think there was an unwritten assumption that forked packages in getsentry will always remain compatible and that just isn't true here due to metrics being a big feature added in the fork.  (and undoing that isn't safe either because there's code depending on the metrics functionality in the fork being there implicitly) :S
```