ref: move TRANSITION_AFTER_DAYS constant to fix sentry.monitoring.queues cycle (#69987)
```
src/sentry/monitoring/queues.py:110: error: Import cycle from Django settings module prevents type inference for 'CELERY_QUEUES'  [misc]
```

doesn't look like much here but it's a step towards django-stubs 5.x

will follow up with the one usage in `getsentry` -- though it will still
work due to the import being preserved

<!-- Describe your PR here. -->