ref: fix test pollution caused by provider class mutation (#88202)
previously failing with:

```console
$ pytest tests/sentry/integrations/test_pipeline.py::FinishPipelineTestCase::test_existing_identity_becomes_default_auth_on_new_orgintegration tests/sentry/web/frontend/test_integration_setup.py::ExampleIntegrationTest::test_basic_flow
============================= test session starts ==============================
platform linux -- Python 3.13.2, pytest-8.1.2, pluggy-1.5.0
django: version: 5.1.7
rootdir: /home/asottile/workspace/sentry
configfile: pyproject.toml
plugins: cov-4.0.0, metadata-3.1.1, rerunfailures-15.0, pytest_sentry-0.3.0, django-4.9.0, time-machine-2.16.0, json-report-1.5.0, xdist-3.0.2, fail-slow-0.3.0, anyio-3.7.1
collected 2 items                                                              

tests/sentry/integrations/test_pipeline.py .                             [ 50%]
tests/sentry/web/frontend/test_integration_setup.py F                    [100%]

=================================== FAILURES ===================================
____________________ ExampleIntegrationTest.test_basic_flow ____________________
tests/sentry/web/frontend/test_integration_setup.py:17: in test_basic_flow
    resp = self.client.post(self.setup_path, {"name": "test"})
.venv/lib/python3.13/site-packages/django/test/client.py:1158: in post
    response = super().post(
.venv/lib/python3.13/site-packages/django/test/client.py:503: in post
    return self.generic(
.venv/lib/python3.13/site-packages/django/test/client.py:676: in generic
    return self.request(**r)
.venv/lib/python3.13/site-packages/django/test/client.py:1092: in request
    self.check_exception(response)
.venv/lib/python3.13/site-packages/django/test/client.py:805: in check_exception
    raise exc_value
.venv/lib/python3.13/site-packages/django/core/handlers/exception.py:55: in inner
    response = get_response(request)
.venv/lib/python3.13/site-packages/django/core/handlers/base.py:197: in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
.venv/lib/python3.13/site-packages/django/views/generic/base.py:104: in view
    return self.dispatch(request, *args, **kwargs)
.venv/lib/python3.13/site-packages/django/utils/decorators.py:48: in _wrapper
    return bound_method(*args, **kwargs)
.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py:65: in _view_wrapper
    return view_func(request, *args, **kwargs)
src/sentry/web/frontend/base.py:406: in dispatch
    return self.handle(request, *args, **kwargs)
src/sentry/web/frontend/pipeline_advancer.py:60: in handle
    response = pipeline.current_step()
src/sentry/pipeline/base.py:184: in current_step
    return self.dispatch_to(step)
src/sentry/pipeline/base.py:192: in dispatch_to
    return step.dispatch(request=self.request, pipeline=self)
src/sentry/integrations/example/integration.py:47: in dispatch
    return pipeline.next_step()
src/sentry/pipeline/base.py:230: in next_step
    return self.current_step()
src/sentry/pipeline/base.py:176: in current_step
    return self.finish_pipeline()
src/sentry/integrations/pipeline.py:155: in finish_pipeline
    response = self._finish_pipeline(data)
src/sentry/integrations/pipeline.py:257: in _finish_pipeline
    raise NotImplementedError("Integration requires an identity")
E   NotImplementedError: Integration requires an identity
----------------------------- Captured stdout call -----------------------------
Traceback (most recent call last):
  File "/home/asottile/workspace/sentry/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/asottile/workspace/sentry/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/asottile/workspace/sentry/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asottile/workspace/sentry/.venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/asottile/workspace/sentry/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/asottile/workspace/sentry/src/sentry/web/frontend/base.py", line 406, in dispatch
    return self.handle(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asottile/workspace/sentry/src/sentry/web/frontend/pipeline_advancer.py", line 60, in handle
    response = pipeline.current_step()
  File "/home/asottile/workspace/sentry/src/sentry/pipeline/base.py", line 184, in current_step
    return self.dispatch_to(step)
           ~~~~~~~~~~~~~~~~^^^^^^
  File "/home/asottile/workspace/sentry/src/sentry/pipeline/base.py", line 192, in dispatch_to
    return step.dispatch(request=self.request, pipeline=self)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/asottile/workspace/sentry/src/sentry/integrations/example/integration.py", line 47, in dispatch
    return pipeline.next_step()
           ~~~~~~~~~~~~~~~~~~^^
  File "/home/asottile/workspace/sentry/src/sentry/pipeline/base.py", line 230, in next_step
    return self.current_step()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/asottile/workspace/sentry/src/sentry/pipeline/base.py", line 176, in current_step
    return self.finish_pipeline()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/asottile/workspace/sentry/src/sentry/integrations/pipeline.py", line 155, in finish_pipeline
    response = self._finish_pipeline(data)
  File "/home/asottile/workspace/sentry/src/sentry/integrations/pipeline.py", line 257, in _finish_pipeline
    raise NotImplementedError("Integration requires an identity")
NotImplementedError: Integration requires an identity
14:38:26 [ERROR] django.request: Internal Server Error: /extensions/example/setup/ (status_code=500 request=<WSGIRequest: POST '/extensions/example/setup/'>)
=========================== short test summary info ============================
FAILED tests/sentry/web/frontend/test_integration_setup.py::ExampleIntegrationTest::test_basic_flow - NotImplementedError: Integration requires an identity
========================= 1 failed, 1 passed in 8.97s ==========================
```

<!-- Describe your PR here. -->